ENABLE_BACKUP=false

BORDER_RADIUS="10"
SHADOW_COLOR="#000000"
SHADOW_SIZE="80x10+0+10"
BORDER_COLOR="#A8D7FE"
BORDER_SIZE=60

SCREENSHOTS_PATH="/sdcard/DCIM/Screenshots"
BACKUP_PATH="${HOME}/.backup/fancyshot"
LOG_PATH="${HOME}/.logs"
